<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PaymentsController extends Controller
{
    /**
     * Show the recent payments activity.
     *
     * @return \Illuminate\Http\Response
     */
    public function recent()
    {
		$payments = array(
								array(
									'id'			=> '1',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 5.40,
									'status'		=> 'completed',												
								),
								array(
									'id'			=> '2',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 100.00,
									'status'		=> 'pending',												
								),
								array(
									'id'			=> '3',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'failed',												
								),
								array(
								
									'id'			=> '4',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'refunded',												
								),
								array(
								
									'id'			=> '5',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'completed',												
								),
								array(
									'id'			=> '6',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'verified',												
								),
								array(
									'id'			=> '7',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'mastercard',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1123.00,
									'status'		=> 'completed',												
								),
								array(
									'id'			=> '8',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'pending',												
								),
								array(
									'id'			=> '9',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'jcb',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1123.00,
									'status'		=> 'failed',												
								),
								array(
									'id'			=> '10',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'completed',												
								),
								array(
									'id'			=> '11',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 122.00,
									'status'		=> 'refunded',												
								),
								array(
									'id'			=> '12',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'paypal',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 5444.00,
									'status'		=> 'completed',												
								),
								array(
									'id'			=> '13',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 8.00,
									'status'		=> 'failed',												
								),
								array(
									'id'			=> '14',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'completed',												
								),
								array(
									'id'			=> '15',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'verified',												
								),
								array(
									'id'			=> '16',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'completed',												
								),
								array(
									'id'			=> '17',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'completed',												
								),
								array(
									'id'			=> '18',
									'date'			=> '08/11/2018',
									'client'		=> 'First Name Last Name',
									'tid'			=> 6167455112,
									'cardtype'	=> 'visa',
									'cardnum'	=> '•••2205',
									'cardexp'	=> '12/21',
									'currency'	=> '$',
									'amount'	=> 1.00,
									'status'		=> 'refunded',												
								),
							);
		
        return $payments; 
    } 	
}
